#!/usr/bin/env bash
# worktree-bootstrap.sh — Copy gitignored env/config files into a fresh worktree.
#
# Git worktrees do not copy gitignored files, so a new worktree is missing the
# .env files (and a couple of other local config files) needed to build and test
# the web, mobile, and desktop apps. Run this once after `pnpm install` in a new
# worktree to copy them from the main repo.
#
# Usage:
#   bash scripts/worktree-bootstrap.sh
#
# Env:
#   DRAFTO_MAIN_REPO   Source repo to copy from (default: /Users/jakub/code/drafto)

set -euo pipefail

SRC="${DRAFTO_MAIN_REPO:-/Users/jakub/code/drafto}"

# Destination is the current worktree root.
if ! DEST="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "error: not inside a git repository" >&2
  exit 1
fi

# Normalise both paths so the self-copy guard compares cleanly.
SRC="$(cd "$SRC" 2>/dev/null && pwd)" || {
  echo "error: source repo not found: ${DRAFTO_MAIN_REPO:-/Users/jakub/code/drafto}" >&2
  exit 1
}

if [ "$SRC" = "$DEST" ]; then
  echo "Nothing to do: already in the main repo ($SRC) — env files are already present."
  exit 0
fi

# Files to copy, relative to the repo root. local.properties is handled
# separately because it only applies once android/ has been prebuilt.
FILES=(
  "apps/web/.env.local"
  "apps/web/.env.local.vercel"
  "apps/mobile/.env"
  "apps/mobile/.env.production"
  "apps/desktop/.env"
  "apps/desktop/.env.production"
  "apps/mobile/google-play-service-account.json"
)

copied=0
skipped=0

echo "Bootstrapping worktree env/config files"
echo "  from: $SRC"
echo "  into: $DEST"
echo

for rel in "${FILES[@]}"; do
  if [ -f "$SRC/$rel" ]; then
    mkdir -p "$DEST/$(dirname "$rel")"
    cp -p "$SRC/$rel" "$DEST/$rel"
    echo "  copied   $rel"
    copied=$((copied + 1))
  else
    echo "  skipped  $rel (not in source)"
    skipped=$((skipped + 1))
  fi
done

# android/ is generated by `expo prebuild`; only copy local.properties when the
# worktree already has it, otherwise prebuild will regenerate the directory.
rel="apps/mobile/android/local.properties"
if [ -f "$SRC/$rel" ]; then
  if [ -d "$DEST/apps/mobile/android" ]; then
    cp -p "$SRC/$rel" "$DEST/$rel"
    echo "  copied   $rel"
    copied=$((copied + 1))
  else
    echo "  skipped  $rel (apps/mobile/android not prebuilt yet — will regenerate)"
    skipped=$((skipped + 1))
  fi
fi

echo
echo "Done: $copied copied, $skipped skipped."
